spring.application.name=ussd event processor

# ========================== Database ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/ussd
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================== JPA ==========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# ========================== Flyway ==========================
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=true

# ========================== Custom Properties ==========================
cdr.watch-folder= ./data/ussd/incoming
cdr.processed-folder=./data/ussd/processed
cdr.poll-rate-ms=60000

# ========================== Logging ==========================
logging.level.com.yourco.cdrloader=INFO